- name: Check passwordless SSH connection is setup
  hosts: scale_nodes
  any_errors_fatal: true
  gather_facts: false
  connection: local
  vars:
    myfile: /root/.ssh
    # - action: pin
  tasks:
  # - command: "ls {{myfile}}"
  #   register: dir_out
  #   until: "dir_out is not failed"
  #   retries: 3
  #   delay: 3
  # - debug: var={{item}}
  #   with_items: dir_out.stdout_lines
  # - name: create empty file
  #   file:
  #     path: /root/jay.txt
  #     state: touch


  - name: Check passwordless SSH on all scale inventory hosts
    shell: ssh {{ ansible_ssh_common_args }} -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/.schematics/IBM/tf_data_path/id_rsa root@{{ inventory_hostname }} "echo PASSWDLESS_SSH_ENABLED"
    register: result
    until: result.stdout.find("PASSWDLESS_SSH_ENABLED") != -1
    # retries: 60
    # delay: 10
  - debug:
      msg: "{{ result }}"
      #until: result.stdout.find("PASSWDLESS_SSH_ENABLED") != -1
      #retries: 30
      #delay: 10
  # - name: Multi Install
  #   become: true
  #   become_user: root
  #   yum:
  #     name: ['git', 'wget']
  #     state: present
  #     update_cache: yes






# - name: Check passwordless SSH connection is setup
#   hosts: scale_nodes
#   any_errors_fatal: true
#   gather_facts: false
#   connection: local
#   vars:
#     myfile: /etc/ssh
#     #- action: pin
#   tasks:
#   - name: check if a file exists
#     ansible.builtin.stat:
#       path: "{{ myfile }}"
#     register: file_data
#   - name: report file exists
#     ansible.builtin.debug:
#       msg: "The file {{ myfile }} exist"
#     when: file_data.stat.exists
#   - name: report file not exists
#     ansible.builtin.debug:
#       msg: "The file {{ myfile }} doesn't exist"
#     when: not file_data.stat.exists


  # - command: "ls {{myfile}}"
  #   register: dir_out
  #   until: "dir_out is not failed"
  #   retries: 3
  #   delay: 3

  # - debug: var={{item}}
  #   with_items: dir_out.stdout_lines

  # - name: Check passwordless SSH on all scale inventory hosts
  #   shell: ssh -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/.schematics/IBM/tf_data_path/id_rsa {{ inventory_hostname }} "echo PASSWDLESS_SSH_ENABLED"
  #   register: result
  #   until: result.stdout.find("PASSWDLESS_SSH_ENABLED") != -1
  #   # retries: 60
  #   # delay: 10
  # - debug:
  #     msg: "{{ result }}"
  #     #until: result.stdout.find("PASSWDLESS_SSH_ENABLED") != -1
  #     #retries: 30
  #     #delay: 10
  # # - name: Multi Install
  # #   become: true
  # #   become_user: root
  # #   yum:
  # #     name: ['git', 'wget']
  # #     state: present
  # #     update_cache: yes
