- name: Check passwordless SSH connection is setup
  hosts: scale_nodes
  any_errors_fatal: true
  gather_facts: false
  connection: local
  tasks:
    # - action: ping
  - name: Check passwordless SSH on all scale inventory hosts
    shell: ssh {{ ansible_ssh_common_args }} -i /tmp/.schematics/IBM/tf_data_path/id_rsa {{ inventory_hostname }} "echo PASSWDLESS_SSH_ENABLED"
    register: result
    until: result.stdout.find("PASSWDLESS_SSH_ENABLED") != -1
    # retries: 60
    # delay: 10
  - debug:
      msg: "{{ result }}"
      #until: result.stdout.find("PASSWDLESS_SSH_ENABLED") != -1
      #retries: 30
      #delay: 10
